RMX2020_defconfig: Enable missing kernel configs required for FCM level 6
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_CRYPTO_CHACHA20POLY1305
    Missing config CONFIG_SONY_FF

Signed-off-by: Koushik Dey <kousickdey3@gmail.com>
Change-Id: I3b60d842eec1715fb8ca58c3fbbeff2c40d98243